name: Format
on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install
    - run: bunx dprint fmt
    - env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "style: format code"
          git push
        fi
